version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:
    commands:
      - sudo yum update -y
      - sudo yum install java-11-amazon-corretto -y
      - sudo wget http://repos.fedorapeople.org/repos/dchen/apache-maven/epel-apache-maven.repo -O /etc/yum.repos.d/epel-apache-maven.repo
      - sudo sed -i s/\$releasever/6/g /etc/yum.repos.d/epel-apache-maven.repo
      - sudo yum install apache-maven -y
  build:
    commands:
      - mvn clean install
  post_build:
    commands:
      - echo Build Completed
artifacts:
  files:
    - target/*.jar
    - scripts/*.sh
    - appspec.yml
  discard-paths: yes