version: 0.2

phases:
  install:
    - sudo wget http://repos.fedorapeople.org/repos/dchen/apache-maven/epel-apache-maven.repo -O /etc/yum.repos.d/epel-apache-maven.repo
    - sudo sed -i s/\$releasever/6/g /etc/yum.repos.d/epel-apache-maven.repo
    - sudo yum install apache-maven
    runtime-versions:
      java: corretto11

  build:
    commands:
      - mvn -Pprod clean verify
    post_build:
      commands:
        - echo Build Completed
artifacts:
  files:
    - target/*.jar
    - scripts/*.sh
    - appspec.yml
  discard-paths: yes