version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11

  build:
    commands:
      - sudo yum update -y
      - sudo yum install -y gcc-c++ make
      - curl -sL https://rpm.nodesource.com/setup_12.x | sudo -E bash -
      - sudo yum install -y nodejs
      - npm install yarn -g
      - pwd
      - cd /tmp
      - sudo wget https://downloads.apache.org/maven/maven-3/3.8.6/binaries/apache-maven-3.8.6-bin.tar.gz
      - sudo tar xf /tmp/apache-maven-*.tar.gz -C /opt
      - sudo ln -s /opt/apache-maven-3.8.1 /opt/maven
      - mvn -version
      - cd /home
      - mvn clean install
    post_build:
      commands:
        - echo Build Completed
artifacts:
  files:
    - target/*.jar
    - scripts/*.sh
    - appspec.yml
  discard-paths: yes